### PR TITLE
Added attendee detail overlay for the Availability component

### PR DESCRIPTION
**Pull request by ozsivanov**
# What you did:

- [x] Added attendee detail popup that displays contact avatar, name, and email address
- [x] Added `attendees_to_show` property that can be used to limit the size of the overlay (shows `+X more` for attendee overflow)

A few remaining TODOs for feature completion:
 - Allow clicking to toggle the overlay
 - Load contact data from Nylas API if no data is provided to the component directly
 - Consider migrating overlay into separate svelte component
 
 
hover

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by philrenaud — CHANGES_REQUESTED** [review]
Hey -- this looks good, but upon trying to select an event (allow_booking set to true), I no longer can do so.

**Comment by ozsivanov** [comment]
> Hey -- this looks good, but upon trying to select an event (allow_booking set to true), I no longer can do so.

Oh good catch, I'll look into fixing this

**Review by chantalala — COMMENTED** [review]
Hey @ozsivanov, this is looking great! Thank you. Aside from the "+- 2 more" issue mentioned on Slack, there's a few other minor changes:

- Let's add `border-radius: 4px` to the overlay corners and update the `box-shadow` color to `rgba(0, 0, 0, 0.25);` instead of pure black
image
- Can we style the dividing lines to match `border: 1px solid #979797;` It looks like it's actually 2px in width right now (it should be the same thickness as the dividing lines in the calendar)
image

**Review by heathergh — COMMENTED** [review]
Hey, I noticed that the available calendar tooltip gets a little cut off when there are multiple days. Not sure if this is an easy fix or not. If it's too much effort, feel free to add to the outstanding tasks/related stories :) Great work!

**Review by heathergh — APPROVED** [review]

**Review by wonka-lighthouse — COMMENTED** [review]
| Device | URL |
|--|--|
| mobile | http://localhost:8000/components/agenda/src/index.html |

     
| Device | URL |
|--|--|
| mobile | http://localhost:8000/components/composer/src/index.html |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Review by philrenaud — APPROVED** [review]

**Pull request merged**
