### PR TITLE
Switched type declaration files to TS files

### PR DESCRIPTION
**Pull request by pooja169usp**
# Background:
enums cannot be imported into JS/TS files from declaration files. We switched declaration file `Availability.d.ts` to `Availability.ts` for Availability component.
In order to be consistent and follow imported TS implementation for all components, we are making this switch.

# Implementation:
- Moved `types` folder under `commons/src/types` from directly under the root `/commons/types`
- Switched type declaration files to TS files
- Updated type references throughout the codebase with `import type` 
- Extracted enums into enums folder under src `commons/src/enums` - (This allows us to auto import enums & types correctly in the code, better dev exp)
- Deleted `Flux.d.ts` & `Api.d.ts` declaration files which are not used/referenced anymore

# ClubHouse Story:
- [Story](https://app.clubhouse.io/nylas/story/65189/components-move-types-from-declaration-files-to-ts-files)
# Readiness checklist

- [X] Cypress tests passing?

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by wonka-lighthouse — COMMENTED** [review]
| Device | URL |
|--|--|
| mobile | http://localhost:8000/components/agenda/src/index.html |

     
| Device | URL |
|--|--|
| mobile | http://localhost:8000/components/composer/src/index.html |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by ozsivanov** [comment]
Hey @pooja169usp, looks great! Is there a reason why we're keeping all of the types files in `@commons`? Could we move the component-specific typings into their component folders, and just keep shared typings in commons?

**Comment by AaronDDM** [comment]
> Hey @pooja169usp, looks great! Is there a reason why we're keeping all of the types files in `@commons`? Could we move the component-specific typings into their component folders, and just keep shared typings in commons?

I didn't think of this! 👍 for this

**Comment by pooja169usp** [comment]
@ozsivanov @AaronDDM All our connections, store etc for each component is within common and we are importing types in connections & store. For e.g.: [here](https://github.com/nylas/components/blob/24b1b5784c5dab72f619f52f80ae0a5ddc0db3db/commons/src/connections/availability.ts#L7-L10)
If we moved this to within components, we will then need to import it from there into common/src/connections or common/src/store, which is not a good idea. So, leaving it in as is.

**Review by philrenaud — APPROVED** [review]

**Review by ozsivanov — APPROVED** [review]

**Review by AaronDDM — APPROVED** [review]

**Pull request merged**
