### PR TITLE
Reworked internal component properties to be accessed through internal _this object

### PR DESCRIPTION
**Pull request by ozsivanov**
# Code changes

- Replace `internalProps` with `_this`
- Removed component-level property to `interalProps` matching
- Added extra undefined checks since `_this` props aren't loaded until after the first tick

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by philrenaud** [comment]
Noticing an inconsistency with _this in ScheduleEditor: it's not inheriting `event_title` from the editor manifest, instead falling back to the default `Meeting`.
image
image

**Comment by philrenaud** [comment]
An issue found with the Availability demo: it appears that changing the "Days to show" slider does not trigger a further fetch for calendars/availability

**Comment by ozsivanov** [comment]
> An issue found with the Availability demo: it appears that changing the "Days to show" slider does not trigger a further fetch for `calendars/availability`. It does throw things into a "loading" state in the UI, but no XHR is made.

Good catch, I'm pretty sure these were caused by a bad rebase - will fix them up today.

**Comment by philrenaud** [comment]
Verifying: earlier-reported issues around manifest-loading in schedule-editor and availability fetching are now corrected!

**Review by philrenaud — APPROVED** [review]

**Pull request merged**
